name: "Visionect Server"
description: "Home Assistant add-on for Visionect Server"
version: "1.0.0"
slug: "visionect-server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  "8081/tcp": 8081
webui: "http://[HOST]:[PORT:8081]"
startup: services
options: {}
schema: {}
